### ISSUE TITLE
Filtering/pagination/sorting

### ISSUE THREAD

**Issue by Ovyerus** [Sayo-nika/Backend#10]
Basic pagination for users and mods can be done through a `page` query string attribute, however this isn't enough. There should be stuff like filtering via a query, setting limit, and showing how many results there are (I haven't checked if this actually gets returned yet or not), sorting, etc. ala how Discord Bots does it (Oxy should hopefully know what I mean)

**Comment by sr229** [comment]
@martmists has implemented pagination for mods if I remember.

**Comment by sr229** [comment]
Already fulfilled in PR #22. Assigning to Mart as well.

**Comment by Ovyerus** [comment]
Not 100%

**Comment by Ovyerus** [comment]
Forgot to do this, but closed with #26.
