### ISSUE TITLE
Report Queue

### ISSUE THREAD

**Issue by Ovyerus** [Sayo-nika/Backend#13]
This'd bring along different endpoints for viewing unverified mods and mods/users reports (as well as implementing them), and then dealing with them in respective ways

**Comment by martmists** [comment]
Unverified mods already have an endpoint, I'll look into reports later.

**Comment by sr229** [comment]
Unverified mods is already in a rooute called `pending_mods`. Renaming issue to only matter the reports queue

**Comment by sr229** [comment]
Related to #34. replace `content` with `type` as a Enum.
