### ISSUE TITLE
Migrate to TwoFish

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/Backend#23]
Since there has been considerable posts regarding Bcrypt not being secure enough as a password hash, we should migrate immediately away from Bcrypt to AES.

AES has been used by GnuPG for encryption and I think we should use this to prevent password leaks.

[Blog explaining bcrypt's algorithmic weakness](http://www.unlimitednovelty.com/2012/03/dont-use-bcrypt.html).

**Comment by ZudoMC** [comment]
AES is a reversable encryption algorithm, and should not be used to store passwords.

**Comment by Ovyerus** [comment]
I haven't even changed the hash function over to bcrypt, it's still using SHA256 (I believe). And yeah AES is reversible so 👎. That blog post you linked suggested using PKBDF2 or scrypt.

**Comment by sr229** [comment]
We're switching the issue to use TwoFish right now instead.

**Comment by Ovyerus** [comment]
Discussed further on Discord and we decided to stick with bcrypt.
