### ISSUE TITLE
Split API routes into multiple files

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/Backend#9]
We're revisiting this due to a cognitive complexity issue being encountered by @Ovyerus.

While previously the performance tradeoff for this was not reasonable, it makes sense in current development context right now as its literally incoherent and messy figuring out which route is which.

For the next dev iteration, we shall focus on these TODOs:

- [ ] Document some routes in-script
- [x] Split routes into multiple files, Express-style.
   - This would heavily imply routes will be split according to their category and permission requirement.
- [ ] Further standardize the entire application by adding comments on unclear parts.

**Comment by martmists** [comment]
`This would heavily imply routes will be split according to their category and permission requirement.`
This is already the case, but I will rename the files to make it clear what permission level they are.

Documentation will be done as soon as I find the time to do so.

**Comment by Ovyerus** [comment]
Finished in #22
